---
apiVersion: v1
kind: Namespace
metadata:
  name: innsecure
  labels:
    name: innsecure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: innsecure-config
  namespace: innsecure
  labels:
    app: innsecure
data:
  DB_HOST: postgres
  VAULT_SECRET_PROVIDER: "true"
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  VAULT_ROLE_NAME: innsecure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: innsecure
  labels:
    app: innsecure
data:
  01_init.sql: |
    CREATE TABLE "Bookings"
      (
      id UUID PRIMARY KEY NOT NULL,
      hotelid INTEGER NOT NULL,
      arrive TEXT NOT NULL,
      leave TEXT NOT NULL,
      name TEXT NOT NULL
    );
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: innsecure
  labels:
    app: postgres-secret
type: Opaque
data:
  POSTGRES_DB: aW5uc2VjdXJl
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: WVdSdGFXNHhNak0w