apiVersion: v1
kind: ServiceAccount
metadata:
  name: innsecure
  namespace: innsecure
---
apiVersion: v1
kind: Service
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30007
      protocol: TCP
  selector:
    app: innsecure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innsecure
  template:
    metadata:
      labels:
        app: innsecure
    spec:
      serviceAccountName: innsecure
      containers:
        - name: innsecure
          image: form3/innsecure
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: innsecure-config
      initContainers:
        - name: wait-for-vault
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ["while [ $(curl -sw '%{http_code}' ${VAULT_ADDR}/v1/sys/health -o /dev/null) -ne 200 ]; do sleep 10; echo 'Waiting for the vault server...'; done"]
          envFrom:
            - configMapRef:
                name: innsecure-config